name: updatecli
on:
  # Allow to be run manually
  workflow_dispatch:
  schedule:
    # Once per day at midnight UTC
    - cron: '0 0 * * *'
  push:
  pull_request:
jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Diff
        uses: updatecli/updatecli-action@v2.21.0
        with:
          command: diff
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply
        uses: updatecli/updatecli-action@v2.21.0
        if: github.ref == 'refs/heads/master'
        with:
          command: apply
          flags: "--config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml"
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
